source :rubygems

gem 'rails', '= 2.3.8'
gem 'mysql', :require => 'mysql'
gem 'acts-as-taggable-on'
gem 'awesome_nested_set'
gem 'rpx_now'
gem 'authlogic'
gem 'authlogic_rpx'
gem 'json'
gem 'cancan'
gem 'compass'
gem 'haml'
gem 'delocalize'
gem 'feedzirra'
gem 'friendly_id'
gem 'jrails'
gem 'paperclip'
gem 'russian'
gem 'will_paginate'
gem 'thinking-sphinx', :require => 'thinking_sphinx'
gem 'www-delicious'
# gem 'rails-footnotes'
gem 'validates_captcha'
gem 'auto_complete_jquery', :git => 'git://github.com/mreinsch/auto_complete_jquery.git'
#TODO Перекинуть ruby-debug в development mode
gem 'ruby-debug'
