# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.26

require 'digest/sha1'
require 'yaml'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end
  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  ENV_LOADED   = true
  LOCKED_BY    = '0.9.26'
  FINGERPRINT  = "a245ddc116c7b66f4b46186a460d9c981a497849"
  HOME         = '/home/woto/.bundle/ruby/1.8/bundler'
  AUTOREQUIRES = {:default=>[["acts-as-taggable-on", false], ["authlogic", false], ["rpx_now", false], ["authlogic_rpx", false], ["auto_complete_jquery", false], ["awesome_nested_set", false], ["cancan", false], ["haml", false], ["compass", false], ["delocalize", false], ["feedzirra", false], ["friendly_id", false], ["jrails", false], ["mysql", true], ["paperclip", false], ["rails", false], ["russian", false], ["thinking_sphinx", true], ["validates_captcha", false], ["will_paginate", false], ["www-delicious", false]]}
  SPECS        = [
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/rake-0.8.7.gemspec", :name=>"rake"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/activesupport-2.3.8.gemspec", :name=>"activesupport"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/rack-1.1.0.gemspec", :name=>"rack"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.8/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/actionpack-2.3.8.gemspec", :name=>"actionpack"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.8/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/actionmailer-2.3.8.gemspec", :name=>"actionmailer"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/activerecord-2.3.8.gemspec", :name=>"activerecord"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/activeresource-2.3.8/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/activeresource-2.3.8.gemspec", :name=>"activeresource"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/acts-as-taggable-on-2.0.6/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/acts-as-taggable-on-2.0.6.gemspec", :name=>"acts-as-taggable-on"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/after_commit-1.0.7/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/after_commit-1.0.7.gemspec", :name=>"after_commit"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/authlogic-2.1.5/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/authlogic-2.1.5.gemspec", :name=>"authlogic"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/json_pure-1.4.3/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/json_pure-1.4.3.gemspec", :name=>"json_pure"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/rpx_now-0.6.21/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/rpx_now-0.6.21.gemspec", :name=>"rpx_now"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/authlogic_rpx-1.1.1/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/authlogic_rpx-1.1.1.gemspec", :name=>"authlogic_rpx"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/bundler/gems/auto_complete_jquery-39f3884252428f0100769dea84dc59e06cfbf676-3f54099c12759d19b62dfa5445a3f9f0c510708c/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/bundler/gems/auto_complete_jquery-39f3884252428f0100769dea84dc59e06cfbf676-3f54099c12759d19b62dfa5445a3f9f0c510708c/auto_complete_jquery.gemspec", :name=>"auto_complete_jquery"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/awesome_nested_set-1.4.3/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/awesome_nested_set-1.4.3.gemspec", :name=>"awesome_nested_set"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/builder-2.1.2/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/builder-2.1.2.gemspec", :name=>"builder"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/cancan-1.1.1/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/cancan-1.1.1.gemspec", :name=>"cancan"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/haml-3.0.12/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/haml-3.0.12.gemspec", :name=>"haml"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/compass-0.10.2/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/compass-0.10.2.gemspec", :name=>"compass"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/curb-0.7.6/lib", "/home/woto/.bundle/ruby/1.8/gems/curb-0.7.6/ext"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/curb-0.7.6.gemspec", :name=>"curb"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/delocalize-0.2.0/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/delocalize-0.2.0.gemspec", :name=>"delocalize"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/nokogiri-1.4.2/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/nokogiri-1.4.2.gemspec", :name=>"nokogiri"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/loofah-0.4.7/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/loofah-0.4.7.gemspec", :name=>"loofah"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/sax-machine-0.0.15/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/sax-machine-0.0.15.gemspec", :name=>"sax-machine"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/feedzirra-0.0.23/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/feedzirra-0.0.23.gemspec", :name=>"feedzirra"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/friendly_id-3.0.6/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/friendly_id-3.0.6.gemspec", :name=>"friendly_id"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/jrails-0.6.0/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/jrails-0.6.0.gemspec", :name=>"jrails"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/mysql-2.8.1/lib", "/usr/lib/ruby/gems/1.8/gems/mysql-2.8.1/ext"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/mysql-2.8.1.gemspec", :name=>"mysql"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/paperclip-2.3.3/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/paperclip-2.3.3.gemspec", :name=>"paperclip"},
        {:load_paths=>["/usr/lib/ruby/gems/1.8/gems/rails-2.3.8/lib"], :loaded_from=>"/usr/lib/ruby/gems/1.8/specifications/rails-2.3.8.gemspec", :name=>"rails"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/riddle-1.0.10/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/riddle-1.0.10.gemspec", :name=>"riddle"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/russian-0.2.7/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/russian-0.2.7.gemspec", :name=>"russian"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/thinking-sphinx-1.3.17/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/thinking-sphinx-1.3.17.gemspec", :name=>"thinking-sphinx"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/validates_captcha-0.9.7/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/validates_captcha-0.9.7.gemspec", :name=>"validates_captcha"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/will_paginate-2.3.14/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/will_paginate-2.3.14.gemspec", :name=>"will_paginate"},
        {:load_paths=>["/home/woto/.bundle/ruby/1.8/gems/www-delicious-0.3.0/lib"], :loaded_from=>"/home/woto/.bundle/ruby/1.8/specifications/www-delicious-0.3.0.gemspec", :name=>"www-delicious"},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    lockfile = File.expand_path('../../Gemfile.lock', __FILE__)
    lock_print = YAML.load(File.read(lockfile))["hash"] if File.exist?(lockfile)
    gem_print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))

    unless gem_print == lock_print
      abort 'Gemfile changed since you last locked. Please run `bundle lock` to relock.'
    end

    unless gem_print == FINGERPRINT
      abort 'Your bundled environment is out of date. Run `bundle install` to regenerate it.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless defined?(Bundler::GEM_LOADED)
end
