defaults: &defaults
  site_name: "Кладовочка программиста"
  site_url: "http://localhost"
  noreply_email: "noreply@localhost"
  noreply_name: "noreply"
  default_url_options: "localhost:3000"
  rpx_app_name: "woto-netbook"
  rpx_api_key: "c61472630802726ce1faedc5a8ace1c50fa53994"
  delicious:
    login: "woto"
    password: "qwer3322"
  github: "http://github.com/woto.atom"
  google_reader: "http://www.google.com/reader/public/atom/user/03958211105266633351/state/com.google/broadcast"
  vimeo: "http://vimeo.com/woto/videos/rss"
  flickr: "http://api.flickr.com/services/feeds/photos_public.gne?id=48576382@N06&lang=en-us&format=rss_200"

development:
  <<: *defaults


production:
  <<: *defaults
