development: &defaults
  site_name: "Мегаблог"
  site_url: "http://localhost"
  noreply_email: "noreply@localhost"
  noreply_name: "noreply"
  default_url_options: "localhost:3000"
  rpx_app_name: "woto-netbook"
  rpx_api_key: "c61472630802726ce1faedc5a8ace1c50fa53994"

production:
  <<: *defaults
