:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/plugins/*/app/javascripts
:source_files:
  - app/javascripts/application.js
  - app/javascripts/prototype.js
  - app/javascripts/effects.js
  - app/javascripts/dragdrop.js
  - app/javascripts/controls.js
  - app/javascripts/weakling.js
  - app/javascripts/*.js
  - app/javascripts/**/*.js
