:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/plugins/*/app/javascripts
:source_files:
  - app/javascripts/application.js
  - app/javascripts/jquery.min.js
  - app/javascripts/jquery.ui.min.js
  - app/javascripts/jrails.min.js
  - public/components/dyndatetime/src/jquery.dynDateTime.js
  - public/components/dyndatetime/lang/calendar-ru.js
  #- app/javascripts/*.js
  #- app/javascripts/**/*.js
